### ISSUE TITLE
Featured subjects and locations on home page

### ISSUE THREAD

**Issue by dcnb** [CollectionBuilder/cb-docs#4]
How many times have we actually used this feature? 

Is there a way to abstract this to just one "featured links" or featured browse links at the bottom of the home section in theme and then simplify the other options? It's a lot of space on the theme and it makes home-inforgraphic much more complicated than needed. 

And I don't think I've ever used it.

**Comment by evanwill** [comment]
could you clarify a bit what you mean? 
Like on home-infographic remove the two boxes with default subjects and locations, and have just one box? 
Or do you mean just simplifying the theme.yml options? 

I use the theme.yml pretty regularly to change which fields are used to gen the boxes, usually adding extras or when "subject" isn't used in the collection. 
I manually tweak the include on home-infographic pretty often to change the title of the boxes if doing something with a different field.

**Comment by dcnb** [comment]
Not the whole feature, just simplifying to get rid of the "featured
subjects" option to feed in any subject you want. I think that complicates
both the theme.yml and the home infographic.

The other subjects and locations portions are fine, and keeping the two
boxes on the home page is good too. Just having those variables in the
liquid code always makes it more difficult to change. And I don't think
even having the max there is very helpful. We could just get rid of that
too.

I don't know. I just think we might rethink those options a bit, and how we
config the home page. I don't feel like we have the right balance. I was
telling Olivia maybe we need a config-home.csv ...

**Comment by evanwill** [comment]
Looking at the include again--realized it was changed from earlier iterations-- I was thinking the field use was still configured in "theme.yml", which apparently is not any more. 
So yeah, if we aren't configuring the filed in theme.yml, not sure why it is worth configuring anything else in there. I think it used to pull in the fields from theme.subject-fields / theme.location-fields, so then it makes sense configuring everything in theme (or if we put the field choice in theme).
But if it isn't doing that--i.e. as currently has the field hard coded in the include, then yeah, pulling in the theme values for other stuff seems stupid, and would be easier to just have hard corded include values that some one could update.
I think mayb

**Comment by evanwill** [comment]
Should we:

- [ ] a. delete all the options out of "theme.yml" and hard code the includes with default options
- [ ] b. put the field configuration back into theme.yml

a. would look like:

`{% include index/featured-terms.html field="subject" title="Top Subjects" btn-color="info" max=5 %}`

b. would look like:

`{% include index/featured-terms.html field="site.data.theme.featured-subjects-fields" title="Top Subjects" btn-color="info" featured=site.data.theme.featured-subjects max=site.data.theme.featured-subjects-max %}`

I believe "a" is sort of a half step towards what @dcnb was meaning, but would still make it easy to customize?

**Comment by owikle** [comment]
I like option A!

**Comment by dcnb** [comment]
A. For sure!

**Comment by evanwill** [comment]
okay, it doing it!

**Comment by evanwill** [comment]
option a is the way now, in -gh and -cdm, will add to -csv and -sa today. already updated the docs. just keep in mind "theme.yml" is shorter now!
