### ISSUE TITLE
config nav link

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/cb-docs#7]
current columns `display_name,stub,dropdown_parent`

should `stub` just be `link`??

**Comment by owikle** [comment]
Yeah, seems more intuitive to beginners

**Comment by evanwill** [comment]
okay. doing it. (don't really remember why it was that way?)

**Comment by evanwill** [comment]
@dcnb @owikle wait, I tweaked the documentation to use `link` instead of `stub`, but didn't update any templates yet--one more chance to confirm--is it a bad a idea to change this? Only negative I see is potential to break some existing configs people created, but very easy fix, and not very likely case?

**Comment by evanwill** [comment]
okay-- cold feet. switching it back to `stub` at least for now!
